# Generated by Django 3.0.7 on 2020-06-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20200613_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completiontime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
