# Generated by Django 3.0.7 on 2020-06-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_auto_20200613_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='author',
            new_name='user',
        ),
    ]
